# app/chain/steps.py
#
# This file contains all Runnable steps used in the AI pipeline.
# Currently implemented:
#   - PromptBuilder (Step 1)
#
# Placeholder classes for:
#   - LLMRunner (Step 2)
#   - ResponseParser (Step 3)
#
# These placeholders allow imports, testing, and pipeline assembly
# before the full implementations are added.


from typing import Dict, Any
from pydantic import BaseModel

from app.chain.runnable import Runnable
from app.config import SYSTEM_PROMPT, logger
from app.config import MAX_PROMPT_LENGTH


# ============================================================
# Pydantic models for PromptBuilder input and output
# ============================================================

class PromptBuilderInput(BaseModel):
    """
    Input model for the PromptBuilder step.
    Contains:
    - question: the user's natural-language question
    - stats: dataset statistics (df.describe().to_dict())
    """
    question: str
    stats: Dict[str, Any]


class PromptBuilderOutput(BaseModel):
    """
    Output model for the PromptBuilder step.
    Contains:
    - prompt: the fully constructed prompt string to send to the LLM
    """
    prompt: str


# ============================================================
# PromptBuilder — Step 1 in the Runnable chain
# ============================================================

class PromptBuilder(Runnable[PromptBuilderInput, PromptBuilderOutput]):
    """
    Builds a structured prompt for the LLM.

    Responsibilities:
    - Combine system instructions (from config)
    - Insert dataset statistics
    - Insert the user's question
    - Produce a clean, deterministic prompt string

    This step is intentionally simple and deterministic so it can be
    easily unit-tested in isolation.
    """

    def invoke(self, input: PromptBuilderInput) -> PromptBuilderOutput:
        # Log the incoming question for traceability
        logger.info("PromptBuilder invoked with question='%s'", input.question)

        # Sanity check — statistics must exist
        if not input.stats:
            raise ValueError("PromptBuilder received empty statistics.")

        # Format statistics section
        stats_section = f"Dataset statistics:\n{input.stats}\n"

        # Build the final prompt
        full_prompt = (
            f"{SYSTEM_PROMPT}\n\n"
            f"{stats_section}\n"
            f"User question: {input.question}\n"
            f"Answer in clear and concise Swedish."
        )

        # Prevent oversized promts
        if len(full_prompt) > MAX_PROMPT_LENGTH:
            logger.warning(
                "PromptBuilder aborted: prompt lenght %s exceeds limit %s",
                len(full_prompt),
                MAX_PROMPT_LENGTH
            )
            raise ValueError(
                f"Prompt too long ({len(full_prompt)} chars)."
                f"Maximum allowed is {MAX_PROMPT_LENGTH}."
            )

        return PromptBuilderOutput(prompt=full_prompt)


# ============================================================
# Typed output model for LLMRunner (Step 2)
# ============================================================

class LLMRunnerOutput(BaseModel):
    """
    Output from the LLMRunner step.
    Contains:
    - raw_output: the raw text generated by the model
    """
    raw_output: str


# ============================================================
# Typed output model for ResponseParser (Step 3)
# ============================================================

class ResponseParserOutput(BaseModel):
    """
    Final structured output from the chain.
    This is what the /ai/ask endpoint will return.
    """
    question: str
    answer: str
    model: str


# ============================================================
# Placeholder implementations for upcoming steps
# ============================================================

class LLMRunner(Runnable[PromptBuilderOutput, LLMRunnerOutput]):
    """
    Placeholder implementation.
    The real implementation will call transformers.pipeline.
    """
    def invoke(self, input: PromptBuilderOutput) -> LLMRunnerOutput:
        raise NotImplementedError("LLMRunner not implemented yet.")


class ResponseParser(Runnable[LLMRunnerOutput, ResponseParserOutput]):
    """
    Placeholder implementation.
    The real implementation will parse the model's raw output.
    """
    def invoke(self, input: LLMRunnerOutput) -> ResponseParserOutput:
        raise NotImplementedError("ResponseParser not implemented yet.")
